//! # Power Concentration Index
//!
//! Structural metric that detects unhealthy power concentration in communities.
//! Not behavioral surveillance — measures the SHAPE of power, not the CONTENT
//! of conversations.
//!
//! From Constellation Art. 8: "No person or office shall hold permanent power."
//!
//! ## How It Works
//!
//! Five factors — role concentration (Gini), proposal dominance (Herfindahl),
//! decision influence, information centrality, and exit barriers — combine into
//! a single 0.0–1.0 score. When the score crosses a threshold, every community
//! member is alerted. No individual can suppress the alert.
//!
//! ## Key Design Decisions
//!
//! - **Minimum alert_threshold is 0.9** — communities can tune but never disable.
//! - **Alerts go to ALL members** — not just leaders.
//! - **Critical threshold triggers automatic governance review.**
//! - **Pure computation** — `PowerConcentrationComputer::compute()` takes data in,
//!   produces index out. No side effects.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::error::BulwarkError;
use crate::federation_scope::FederationScope;

// ── Constants ──────────────────────────────────────────────────────────────────

/// The absolute minimum alert threshold. Communities can set a higher bar,
/// but they cannot turn the detector off entirely.
pub const MINIMUM_ALERT_THRESHOLD: f64 = 0.9;

/// Default alert threshold — index above this triggers alert to all members.
pub const DEFAULT_ALERT_THRESHOLD: f64 = 0.6;

/// Default critical threshold — index above this triggers mandatory governance review.
pub const DEFAULT_CRITICAL_THRESHOLD: f64 = 0.8;

/// Default computation interval in hours (168 = weekly).
pub const DEFAULT_COMPUTATION_INTERVAL_HOURS: u64 = 168;

// ── Core Types ─────────────────────────────────────────────────────────────────

/// A snapshot of power concentration within a community.
///
/// Score runs 0.0 (perfectly distributed) to 1.0 (total concentration).
/// Computed periodically by `PowerConcentrationComputer::compute()`.
///
/// # Example
///
/// ```
/// use bulwark::power_index::{PowerConcentrationIndex, PowerFactors, PowerConcentrationConfig};
/// use bulwark::power_index::PowerConcentrationComputer;
///
/// let index = PowerConcentrationComputer::compute(
///     "community_abc",
///     &[vec!["founder".into(), "elder".into()], vec!["member".into()]],
///     &["alice", "alice", "alice", "bob"],
///     &[("alice", true), ("bob", false), ("alice", true)],
///     &[("alice", 10), ("bob", 2), ("carol", 1)],
///     &[0.8, 0.3, 0.1],
///     &PowerConcentrationConfig::default(),
/// );
/// assert!(index.score >= 0.0 && index.score <= 1.0);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PowerConcentrationIndex {
    /// The community this index was computed for.
    pub community_id: String,
    /// Overall concentration score: 0.0 (distributed) to 1.0 (concentrated).
    pub score: f64,
    /// The individual factor scores that produced this index.
    pub factors: PowerFactors,
    /// Alerts generated by crossing thresholds.
    pub alerts: Vec<PowerAlert>,
    /// When this index was computed.
    pub computed_at: DateTime<Utc>,
}

/// The five dimensions of power concentration — each 0.0 to 1.0.
///
/// Higher values indicate more concentration (worse).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PowerFactors {
    /// Gini coefficient of governance role distribution.
    /// One person holding all roles = 1.0. Evenly distributed = 0.0.
    pub role_concentration: f64,
    /// Herfindahl-Hirschman Index of proposal authorship.
    /// One person proposing everything = 1.0. Equal distribution = near 0.0.
    pub proposal_dominance: f64,
    /// How often one person's vote is the deciding vote.
    /// Always deciding = 1.0. Never deciding = 0.0.
    pub decision_influence: f64,
    /// Graph centrality of content authorship.
    /// One person creating all content = 1.0. Diverse authorship = low.
    pub information_centrality: f64,
    /// How much a member would lose by leaving (average exit barrier).
    /// Locked in = 1.0. Free to leave = 0.0.
    pub exit_barrier: f64,
}

impl PowerFactors {
    /// Compute the overall score as the mean of all enabled factors.
    ///
    /// If `factors_enabled` is empty, all factors are used.
    #[must_use]
    pub fn combined_score(&self, factors_enabled: &[String]) -> f64 {
        let all_factors = self.as_named_vec();
        let active: Vec<f64> = if factors_enabled.is_empty() {
            all_factors.iter().map(|(_, v)| *v).collect()
        } else {
            all_factors
                .iter()
                .filter(|(name, _)| factors_enabled.iter().any(|f| f == name))
                .map(|(_, v)| *v)
                .collect()
        };

        if active.is_empty() {
            return 0.0;
        }

        let sum: f64 = active.iter().sum();
        sum / active.len() as f64
    }

    /// Return all factors as (name, value) pairs.
    #[must_use]
    pub fn as_named_vec(&self) -> Vec<(&str, f64)> {
        vec![
            ("role_concentration", self.role_concentration),
            ("proposal_dominance", self.proposal_dominance),
            ("decision_influence", self.decision_influence),
            ("information_centrality", self.information_centrality),
            ("exit_barrier", self.exit_barrier),
        ]
    }
}

/// An alert raised when a factor or the overall index crosses a threshold.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PowerAlert {
    /// Which factor triggered this alert (or "overall" for the combined score).
    pub factor: String,
    /// The value that crossed the threshold.
    pub value: f64,
    /// The threshold that was crossed.
    pub threshold: f64,
    /// Human-readable description of what this means.
    pub description: String,
    /// Recommended action.
    pub recommendation: String,
}

/// Per-community configuration for the power concentration index.
///
/// Stored in the Kingdom Charter. Communities can tune thresholds but
/// cannot disable the index entirely — `alert_threshold` is clamped to
/// at most `MINIMUM_ALERT_THRESHOLD` (0.9).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PowerConcentrationConfig {
    /// Index above this triggers alert to all members.
    /// Clamped to at most `MINIMUM_ALERT_THRESHOLD`.
    pub alert_threshold: f64,
    /// Index above this triggers mandatory governance review.
    pub critical_threshold: f64,
    /// Which factors to compute. Empty = all.
    pub factors_enabled: Vec<String>,
    /// How often to recompute, in hours.
    pub computation_interval_hours: u64,
}

impl PowerConcentrationConfig {
    /// Create a new config, enforcing the minimum alert threshold.
    ///
    /// # Errors
    ///
    /// Returns `BulwarkError::ConfigError` if:
    /// - `critical_threshold` is less than `alert_threshold` (after clamping)
    /// - Thresholds are not in 0.0–1.0 range
    /// - `computation_interval_hours` is 0
    pub fn new(
        alert_threshold: f64,
        critical_threshold: f64,
        factors_enabled: Vec<String>,
        computation_interval_hours: u64,
    ) -> Result<Self, BulwarkError> {
        if !(0.0..=1.0).contains(&alert_threshold) {
            return Err(BulwarkError::ConfigError(
                "alert_threshold must be between 0.0 and 1.0".into(),
            ));
        }
        if !(0.0..=1.0).contains(&critical_threshold) {
            return Err(BulwarkError::ConfigError(
                "critical_threshold must be between 0.0 and 1.0".into(),
            ));
        }
        if computation_interval_hours == 0 {
            return Err(BulwarkError::ConfigError(
                "computation_interval_hours must be > 0".into(),
            ));
        }

        // Enforce minimum: you can't set alert_threshold above MINIMUM_ALERT_THRESHOLD.
        let effective_alert = alert_threshold.min(MINIMUM_ALERT_THRESHOLD);

        if critical_threshold < effective_alert {
            return Err(BulwarkError::ConfigError(format!(
                "critical_threshold ({critical_threshold}) must be >= alert_threshold ({effective_alert})"
            )));
        }

        Ok(Self {
            alert_threshold: effective_alert,
            critical_threshold,
            factors_enabled,
            computation_interval_hours,
        })
    }

    /// The effective alert threshold after applying the minimum clamp.
    #[must_use]
    pub fn effective_alert_threshold(&self) -> f64 {
        self.alert_threshold.min(MINIMUM_ALERT_THRESHOLD)
    }

    /// Validate an existing config (e.g., deserialized from storage).
    ///
    /// # Errors
    ///
    /// Returns `BulwarkError::ConfigError` if the config is invalid.
    pub fn validate(&self) -> Result<(), BulwarkError> {
        if !(0.0..=1.0).contains(&self.alert_threshold) {
            return Err(BulwarkError::ConfigError(
                "alert_threshold must be between 0.0 and 1.0".into(),
            ));
        }
        if !(0.0..=1.0).contains(&self.critical_threshold) {
            return Err(BulwarkError::ConfigError(
                "critical_threshold must be between 0.0 and 1.0".into(),
            ));
        }
        if self.computation_interval_hours == 0 {
            return Err(BulwarkError::ConfigError(
                "computation_interval_hours must be > 0".into(),
            ));
        }
        let effective = self.effective_alert_threshold();
        if self.critical_threshold < effective {
            return Err(BulwarkError::ConfigError(format!(
                "critical_threshold ({}) must be >= effective alert_threshold ({effective})",
                self.critical_threshold
            )));
        }
        Ok(())
    }
}

impl Default for PowerConcentrationConfig {
    fn default() -> Self {
        Self {
            alert_threshold: DEFAULT_ALERT_THRESHOLD,
            critical_threshold: DEFAULT_CRITICAL_THRESHOLD,
            factors_enabled: Vec::new(), // empty = all
            computation_interval_hours: DEFAULT_COMPUTATION_INTERVAL_HOURS,
        }
    }
}

// ── Mathematical Primitives ────────────────────────────────────────────────────

/// Compute the Gini coefficient from a slice of non-negative values.
///
/// Returns 0.0 for perfectly equal distributions, approaches 1.0 for
/// maximum inequality. Returns 0.0 for empty or single-element input.
///
/// Uses the relative mean absolute difference formula:
/// G = (sum of |xi - xj| for all i,j) / (2 * n * sum(xi))
#[must_use]
pub fn gini_coefficient(values: &[f64]) -> f64 {
    let n = values.len();
    if n <= 1 {
        return 0.0;
    }

    let sum: f64 = values.iter().sum();
    if sum == 0.0 {
        return 0.0;
    }

    let mut abs_diff_sum = 0.0;
    for i in 0..n {
        for j in 0..n {
            abs_diff_sum += (values[i] - values[j]).abs();
        }
    }

    abs_diff_sum / (2.0 * n as f64 * sum)
}

/// Compute the normalized Herfindahl-Hirschman Index (HHI) from share counts.
///
/// Input: a slice of counts (e.g., number of proposals per author).
/// Output: 0.0 (perfectly distributed) to 1.0 (one entity has everything).
///
/// The raw HHI is sum(share_i^2) where share_i = count_i / total.
/// Raw HHI ranges from 1/N to 1.0. We normalize to 0.0–1.0:
/// normalized = (HHI - 1/N) / (1 - 1/N)
///
/// Returns 0.0 for empty input. Returns 1.0 for a single entity.
#[must_use]
pub fn herfindahl_index(counts: &[u64]) -> f64 {
    let n = counts.len();
    if n == 0 {
        return 0.0;
    }
    if n == 1 {
        return 1.0;
    }

    let total: u64 = counts.iter().sum();
    if total == 0 {
        return 0.0;
    }

    let total_f = total as f64;
    let hhi: f64 = counts
        .iter()
        .map(|&c| {
            let share = c as f64 / total_f;
            share * share
        })
        .sum();

    let n_f = n as f64;
    let min_hhi = 1.0 / n_f;

    // Normalize: (HHI - 1/N) / (1 - 1/N)
    let normalized = (hhi - min_hhi) / (1.0 - min_hhi);
    normalized.clamp(0.0, 1.0)
}

/// Compute decision influence — how concentrated the "deciding vote" is.
///
/// Input: a slice of (voter_id, was_deciding) tuples.
/// A vote is "deciding" if the outcome would have been different without it.
///
/// We compute the share of deciding votes per voter, then return the maximum
/// share. If one person is always the deciding voter, this approaches 1.0.
/// If deciding votes are evenly spread, this is low.
///
/// Returns 0.0 if there are no deciding votes.
#[must_use]
pub fn decision_influence(votes: &[(&str, bool)]) -> f64 {
    if votes.is_empty() {
        return 0.0;
    }

    let deciding_votes: Vec<&str> = votes
        .iter()
        .filter(|(_, deciding)| *deciding)
        .map(|(voter, _)| *voter)
        .collect();

    let total_deciding = deciding_votes.len();
    if total_deciding == 0 {
        return 0.0;
    }

    // Count deciding votes per voter.
    let mut counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for voter in &deciding_votes {
        *counts.entry(voter).or_default() += 1;
    }

    let max_count = counts.values().max().copied().unwrap_or(0);
    max_count as f64 / total_deciding as f64
}

/// Compute information centrality from content authorship counts.
///
/// Input: a slice of (author_id, content_count) tuples.
/// Uses the same HHI approach as proposal dominance — concentration
/// of content creation.
///
/// Returns 0.0 for empty input or perfectly distributed authorship.
#[must_use]
pub fn information_centrality(authorship: &[(&str, u64)]) -> f64 {
    if authorship.is_empty() {
        return 0.0;
    }

    let counts: Vec<u64> = authorship.iter().map(|(_, count)| *count).collect();
    herfindahl_index(&counts)
}

/// Compute average exit barrier from individual barrier scores.
///
/// Input: a slice of per-member exit barrier scores (each 0.0–1.0).
/// Output: the mean barrier, 0.0–1.0.
///
/// Returns 0.0 for empty input.
#[must_use]
pub fn average_exit_barrier(barriers: &[f64]) -> f64 {
    if barriers.is_empty() {
        return 0.0;
    }

    let sum: f64 = barriers.iter().sum();
    (sum / barriers.len() as f64).clamp(0.0, 1.0)
}

// ── Computer ───────────────────────────────────────────────────────────────────

/// Pure-function computer for power concentration indices.
///
/// Takes raw data arrays in, produces a `PowerConcentrationIndex` out.
/// No side effects. No database access. No network calls.
pub struct PowerConcentrationComputer;

impl PowerConcentrationComputer {
    /// Compute a power concentration index from raw community data.
    ///
    /// # Parameters
    ///
    /// - `community_id` — the community being measured.
    /// - `member_roles` — for each member, a `Vec<String>` of their roles.
    ///   Used to compute role concentration (Gini coefficient of role counts).
    /// - `proposal_authors` — the author ID for each proposal ever submitted.
    ///   Used to compute proposal dominance (Herfindahl index).
    /// - `deciding_votes` — (voter_id, was_deciding) tuples from vote history.
    ///   Used to compute decision influence.
    /// - `content_authorship` — (author_id, content_count) tuples.
    ///   Used to compute information centrality.
    /// - `exit_barriers` — per-member exit barrier scores (each 0.0–1.0).
    ///   Used to compute average exit barrier.
    /// - `config` — the community's `PowerConcentrationConfig`.
    #[must_use]
    pub fn compute(
        community_id: &str,
        member_roles: &[Vec<String>],
        proposal_authors: &[&str],
        deciding_votes: &[(&str, bool)],
        content_authorship: &[(&str, u64)],
        exit_barriers: &[f64],
        config: &PowerConcentrationConfig,
    ) -> PowerConcentrationIndex {
        // Compute each factor.
        let role_concentration = Self::compute_role_concentration(member_roles);
        let proposal_dominance = Self::compute_proposal_dominance(proposal_authors);
        let decision_inf = decision_influence(deciding_votes);
        let info_centrality = information_centrality(content_authorship);
        let exit_bar = average_exit_barrier(exit_barriers);

        let factors = PowerFactors {
            role_concentration,
            proposal_dominance,
            decision_influence: decision_inf,
            information_centrality: info_centrality,
            exit_barrier: exit_bar,
        };

        let score = factors.combined_score(&config.factors_enabled);

        // Generate alerts.
        let effective_alert = config.effective_alert_threshold();
        let mut alerts = Vec::new();

        // Check overall score.
        if score >= config.critical_threshold {
            alerts.push(PowerAlert {
                factor: "overall".into(),
                value: score,
                threshold: config.critical_threshold,
                description: format!(
                    "Power concentration index ({score:.2}) has reached critical level"
                ),
                recommendation:
                    "Mandatory governance review required. Consider redistributing roles and responsibilities."
                        .into(),
            });
        } else if score >= effective_alert {
            alerts.push(PowerAlert {
                factor: "overall".into(),
                value: score,
                threshold: effective_alert,
                description: format!(
                    "Power concentration index ({score:.2}) exceeds alert threshold"
                ),
                recommendation:
                    "Review governance structure. Consider term limits, role rotation, or distributed decision-making."
                        .into(),
            });
        }

        // Check individual factors against the alert threshold.
        for (name, value) in factors.as_named_vec() {
            if value >= config.critical_threshold {
                alerts.push(PowerAlert {
                    factor: name.into(),
                    value,
                    threshold: config.critical_threshold,
                    description: format!(
                        "{name} ({value:.2}) has reached critical concentration"
                    ),
                    recommendation: Self::recommendation_for(name),
                });
            } else if value >= effective_alert {
                alerts.push(PowerAlert {
                    factor: name.into(),
                    value,
                    threshold: effective_alert,
                    description: format!(
                        "{name} ({value:.2}) exceeds alert threshold"
                    ),
                    recommendation: Self::recommendation_for(name),
                });
            }
        }

        PowerConcentrationIndex {
            community_id: community_id.into(),
            score,
            factors,
            alerts,
            computed_at: Utc::now(),
        }
    }

    /// Compute role concentration using the Gini coefficient.
    ///
    /// Each member's "value" is the number of roles they hold.
    /// Gini of 0.0 = everyone has the same number of roles.
    /// Gini of 1.0 = one person holds all roles.
    fn compute_role_concentration(member_roles: &[Vec<String>]) -> f64 {
        if member_roles.is_empty() {
            return 0.0;
        }

        let role_counts: Vec<f64> = member_roles
            .iter()
            .map(|roles| roles.len() as f64)
            .collect();

        gini_coefficient(&role_counts)
    }

    /// Compute proposal dominance using the Herfindahl index.
    ///
    /// Counts proposals per author, then computes normalized HHI.
    fn compute_proposal_dominance(proposal_authors: &[&str]) -> f64 {
        if proposal_authors.is_empty() {
            return 0.0;
        }

        let mut counts: std::collections::HashMap<&str, u64> =
            std::collections::HashMap::new();
        for author in proposal_authors {
            *counts.entry(author).or_default() += 1;
        }

        let count_vec: Vec<u64> = counts.values().copied().collect();
        herfindahl_index(&count_vec)
    }

    /// Filter a set of power indices to only those from visible communities.
    ///
    /// When the scope is unrestricted, all indices pass through.
    pub fn filter_indices_scoped<'a>(
        indices: &'a [PowerConcentrationIndex],
        scope: &FederationScope,
    ) -> Vec<&'a PowerConcentrationIndex> {
        if scope.is_unrestricted() {
            return indices.iter().collect();
        }
        indices
            .iter()
            .filter(|idx| scope.is_visible(&idx.community_id))
            .collect()
    }

    /// Compute the maximum power concentration score across visible communities.
    ///
    /// Useful for answering: "Does this person (or anyone) hold dangerous power
    /// concentrations within this federation?"
    ///
    /// Returns `None` if no indices exist for visible communities.
    pub fn max_concentration_scoped(
        indices: &[PowerConcentrationIndex],
        scope: &FederationScope,
    ) -> Option<f64> {
        indices
            .iter()
            .filter(|idx| scope.is_visible(&idx.community_id))
            .map(|idx| idx.score)
            .reduce(f64::max)
    }

    /// Count communities with alerts in the visible scope.
    ///
    /// Returns the number of federated communities whose power concentration
    /// index has generated at least one alert.
    pub fn communities_with_alerts_scoped(
        indices: &[PowerConcentrationIndex],
        scope: &FederationScope,
    ) -> usize {
        indices
            .iter()
            .filter(|idx| scope.is_visible(&idx.community_id) && !idx.alerts.is_empty())
            .count()
    }

    /// Per-factor recommendation text.
    fn recommendation_for(factor: &str) -> String {
        match factor {
            "role_concentration" => {
                "Consider implementing role limits, term rotation, or distributing governance roles more broadly.".into()
            }
            "proposal_dominance" => {
                "Encourage broader participation in proposal authorship. Consider proposal mentorship or co-authorship programs.".into()
            }
            "decision_influence" => {
                "One person's vote is disproportionately decisive. Consider larger quorum requirements or weighted voting.".into()
            }
            "information_centrality" => {
                "Content creation is concentrated. Encourage diverse authorship and reduce barriers to contribution.".into()
            }
            "exit_barrier" => {
                "Members face high costs to leave. Review economic entanglements and ensure data portability.".into()
            }
            _ => "Review this factor and consider redistribution measures.".into(),
        }
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Gini Coefficient ───────────────────────────────────────────────────

    #[test]
    fn gini_perfect_equality() {
        // Everyone has the same value → Gini = 0.0
        let values = vec![10.0, 10.0, 10.0, 10.0];
        assert_eq!(gini_coefficient(&values), 0.0);
    }

    #[test]
    fn gini_maximum_inequality() {
        // One person has everything, others have nothing.
        // Gini = (n-1)/n for [0, 0, ..., 0, X]
        let values = vec![0.0, 0.0, 0.0, 100.0];
        let expected = 3.0 / 4.0; // 0.75
        assert!((gini_coefficient(&values) - expected).abs() < 1e-10);
    }

    #[test]
    fn gini_empty() {
        assert_eq!(gini_coefficient(&[]), 0.0);
    }

    #[test]
    fn gini_single_element() {
        assert_eq!(gini_coefficient(&[42.0]), 0.0);
    }

    #[test]
    fn gini_all_zeros() {
        assert_eq!(gini_coefficient(&[0.0, 0.0, 0.0]), 0.0);
    }

    #[test]
    fn gini_two_elements() {
        // [0, 10] → Gini = |0-10| + |10-0| / (2 * 2 * 10) = 20 / 40 = 0.5
        let values = vec![0.0, 10.0];
        assert!((gini_coefficient(&values) - 0.5).abs() < 1e-10);
    }

    #[test]
    fn gini_moderate_inequality() {
        // [1, 2, 3, 4, 5] — moderate inequality
        let values = vec![1.0, 2.0, 3.0, 4.0, 5.0];
        let g = gini_coefficient(&values);
        assert!(g > 0.0 && g < 0.5, "Gini should be moderate: {g}");
    }

    // ── Herfindahl-Hirschman Index ─────────────────────────────────────────

    #[test]
    fn hhi_perfect_monopoly() {
        // One entity has everything.
        assert_eq!(herfindahl_index(&[100]), 1.0);
    }

    #[test]
    fn hhi_perfect_distribution() {
        // All entities have equal share. Normalized = 0.0.
        let counts = vec![10, 10, 10, 10];
        assert!((herfindahl_index(&counts)).abs() < 1e-10);
    }

    #[test]
    fn hhi_empty() {
        assert_eq!(herfindahl_index(&[]), 0.0);
    }

    #[test]
    fn hhi_all_zeros() {
        assert_eq!(herfindahl_index(&[0, 0, 0]), 0.0);
    }

    #[test]
    fn hhi_duopoly_unequal() {
        // [90, 10]: shares = [0.9, 0.1], HHI = 0.81 + 0.01 = 0.82
        // min = 0.5, normalized = (0.82 - 0.5) / (1 - 0.5) = 0.64
        let counts = vec![90, 10];
        let hhi = herfindahl_index(&counts);
        let expected = (0.82 - 0.5) / 0.5;
        assert!((hhi - expected).abs() < 1e-10, "HHI: {hhi}, expected: {expected}");
    }

    #[test]
    fn hhi_two_equal() {
        // [50, 50]: normalized should be 0.0
        let counts = vec![50, 50];
        assert!(herfindahl_index(&counts).abs() < 1e-10);
    }

    #[test]
    fn hhi_concentrated_but_not_monopoly() {
        // [70, 20, 10]: moderate concentration
        let hhi = herfindahl_index(&[70, 20, 10]);
        assert!(hhi > 0.3 && hhi < 0.8, "HHI should be moderate: {hhi}");
    }

    // ── Decision Influence ─────────────────────────────────────────────────

    #[test]
    fn decision_influence_single_decider() {
        // One person is always the deciding vote.
        let votes = vec![
            ("alice", true),
            ("bob", false),
            ("alice", true),
            ("carol", false),
        ];
        assert_eq!(decision_influence(&votes), 1.0);
    }

    #[test]
    fn decision_influence_evenly_spread() {
        let votes = vec![
            ("alice", true),
            ("bob", true),
            ("carol", true),
        ];
        let influence = decision_influence(&votes);
        assert!(
            (influence - 1.0 / 3.0).abs() < 1e-10,
            "Expected ~0.333, got {influence}"
        );
    }

    #[test]
    fn decision_influence_no_deciding() {
        let votes = vec![("alice", false), ("bob", false)];
        assert_eq!(decision_influence(&votes), 0.0);
    }

    #[test]
    fn decision_influence_empty() {
        assert_eq!(decision_influence(&[]), 0.0);
    }

    // ── Information Centrality ─────────────────────────────────────────────

    #[test]
    fn information_centrality_single_author() {
        let authorship = vec![("alice", 100)];
        assert_eq!(information_centrality(&authorship), 1.0);
    }

    #[test]
    fn information_centrality_even() {
        let authorship = vec![("alice", 10), ("bob", 10), ("carol", 10)];
        assert!(information_centrality(&authorship).abs() < 1e-10);
    }

    #[test]
    fn information_centrality_empty() {
        assert_eq!(information_centrality(&[]), 0.0);
    }

    // ── Exit Barrier ───────────────────────────────────────────────────────

    #[test]
    fn exit_barrier_high() {
        let barriers = vec![0.9, 0.8, 0.95];
        let avg = average_exit_barrier(&barriers);
        assert!(avg > 0.8, "Expected high exit barrier: {avg}");
    }

    #[test]
    fn exit_barrier_low() {
        let barriers = vec![0.1, 0.05, 0.15];
        let avg = average_exit_barrier(&barriers);
        assert!(avg < 0.2, "Expected low exit barrier: {avg}");
    }

    #[test]
    fn exit_barrier_empty() {
        assert_eq!(average_exit_barrier(&[]), 0.0);
    }

    #[test]
    fn exit_barrier_clamped() {
        // Even with values > 1.0, result is clamped.
        let barriers = vec![1.5, 2.0];
        let avg = average_exit_barrier(&barriers);
        assert_eq!(avg, 1.0);
    }

    // ── Combined Index Scoring ─────────────────────────────────────────────

    #[test]
    fn combined_score_all_factors() {
        let factors = PowerFactors {
            role_concentration: 0.2,
            proposal_dominance: 0.4,
            decision_influence: 0.6,
            information_centrality: 0.3,
            exit_barrier: 0.5,
        };
        let score = factors.combined_score(&[]);
        let expected = (0.2 + 0.4 + 0.6 + 0.3 + 0.5) / 5.0;
        assert!((score - expected).abs() < 1e-10);
    }

    #[test]
    fn combined_score_subset_factors() {
        let factors = PowerFactors {
            role_concentration: 0.8,
            proposal_dominance: 0.2,
            decision_influence: 0.1,
            information_centrality: 0.9,
            exit_barrier: 0.0,
        };
        let enabled = vec!["role_concentration".into(), "information_centrality".into()];
        let score = factors.combined_score(&enabled);
        let expected = (0.8 + 0.9) / 2.0;
        assert!((score - expected).abs() < 1e-10);
    }

    #[test]
    fn combined_score_no_matching_factors() {
        let factors = PowerFactors {
            role_concentration: 0.5,
            proposal_dominance: 0.5,
            decision_influence: 0.5,
            information_centrality: 0.5,
            exit_barrier: 0.5,
        };
        let enabled = vec!["nonexistent_factor".into()];
        assert_eq!(factors.combined_score(&enabled), 0.0);
    }

    // ── Threshold Alerting ─────────────────────────────────────────────────

    #[test]
    fn alerts_generated_when_above_threshold() {
        let config = PowerConcentrationConfig::default();
        // Create a community with high concentration.
        let index = PowerConcentrationComputer::compute(
            "test_community",
            &[
                vec!["founder".into(), "elder".into(), "judge".into()],
                vec![],
                vec![],
                vec![],
            ],
            &["alice", "alice", "alice", "alice", "bob"],
            &[("alice", true), ("alice", true), ("bob", false)],
            &[("alice", 50), ("bob", 2)],
            &[0.7, 0.8, 0.9],
            &config,
        );
        // Should generate alerts for factors above 0.6.
        assert!(
            !index.alerts.is_empty(),
            "Expected alerts for concentrated community"
        );
    }

    #[test]
    fn no_alerts_when_distributed() {
        let config = PowerConcentrationConfig::default();
        let index = PowerConcentrationComputer::compute(
            "healthy_community",
            &[
                vec!["member".into()],
                vec!["member".into()],
                vec!["member".into()],
                vec!["member".into()],
            ],
            &["alice", "bob", "carol", "dave"],
            &[("alice", true), ("bob", true), ("carol", true), ("dave", true)],
            &[("alice", 10), ("bob", 10), ("carol", 10), ("dave", 10)],
            &[0.1, 0.1, 0.1, 0.1],
            &config,
        );
        assert!(
            index.alerts.is_empty(),
            "Expected no alerts for healthy community, got: {:?}",
            index.alerts
        );
        assert!(index.score < 0.3, "Score should be low: {}", index.score);
    }

    #[test]
    fn critical_alert_at_critical_threshold() {
        let config = PowerConcentrationConfig::default();
        // Extreme concentration: one person does everything.
        let index = PowerConcentrationComputer::compute(
            "dictator_community",
            &[
                vec![
                    "founder".into(),
                    "elder".into(),
                    "judge".into(),
                    "moderator".into(),
                ],
                vec![],
                vec![],
            ],
            &["alice", "alice", "alice", "alice", "alice"],
            &[("alice", true), ("alice", true), ("alice", true)],
            &[("alice", 100)],
            &[0.95, 0.95, 0.95],
            &config,
        );
        let critical_alerts: Vec<_> = index
            .alerts
            .iter()
            .filter(|a| a.threshold >= config.critical_threshold)
            .collect();
        assert!(
            !critical_alerts.is_empty(),
            "Expected critical alerts for dictator community"
        );
    }

    #[test]
    fn individual_factor_alerts() {
        // Only one factor is high, others are low.
        let config = PowerConcentrationConfig::default();
        let index = PowerConcentrationComputer::compute(
            "test",
            &[
                vec!["founder".into(), "elder".into(), "judge".into(), "mod".into()],
                vec![],
                vec![],
                vec![],
                vec![],
            ],
            &["alice", "bob", "carol", "dave", "eve"],           // even
            &[("alice", true), ("bob", true), ("carol", true)],  // even
            &[("a", 10), ("b", 10), ("c", 10), ("d", 10)],      // even
            &[0.1, 0.1, 0.1, 0.1, 0.1],                         // low
            &config,
        );
        // role_concentration should be high (one person has 4 roles, others have 0).
        assert!(
            index.factors.role_concentration > 0.5,
            "Role concentration should be high: {}",
            index.factors.role_concentration
        );
        // Other factors should be low.
        assert!(
            index.factors.proposal_dominance < 0.1,
            "Proposal dominance should be low: {}",
            index.factors.proposal_dominance
        );
    }

    // ── Minimum Threshold Enforcement ──────────────────────────────────────

    #[test]
    fn minimum_threshold_enforced_on_new() {
        // Try to set alert_threshold to 0.95 (above the 0.9 min).
        let config =
            PowerConcentrationConfig::new(0.95, 0.98, vec![], 168).expect("valid config");
        // Should clamp to 0.9.
        assert_eq!(config.alert_threshold, MINIMUM_ALERT_THRESHOLD);
    }

    #[test]
    fn minimum_threshold_enforced_below_minimum() {
        // Setting 0.5 is fine — it's below the minimum cap.
        let config = PowerConcentrationConfig::new(0.5, 0.8, vec![], 168).expect("valid config");
        assert_eq!(config.alert_threshold, 0.5);
    }

    #[test]
    fn effective_alert_threshold_clamps_deserialized() {
        // Simulate a deserialized config with a threshold above minimum.
        let config = PowerConcentrationConfig {
            alert_threshold: 0.99,
            critical_threshold: 1.0,
            factors_enabled: vec![],
            computation_interval_hours: 168,
        };
        assert_eq!(config.effective_alert_threshold(), MINIMUM_ALERT_THRESHOLD);
    }

    #[test]
    fn cannot_disable_detector() {
        // Even setting threshold to 1.0, effective is still 0.9.
        let config = PowerConcentrationConfig {
            alert_threshold: 1.0,
            critical_threshold: 1.0,
            factors_enabled: vec![],
            computation_interval_hours: 168,
        };
        assert!(config.effective_alert_threshold() <= MINIMUM_ALERT_THRESHOLD);
    }

    // ── Config Validation ──────────────────────────────────────────────────

    #[test]
    fn config_default_is_valid() {
        let config = PowerConcentrationConfig::default();
        assert!(config.validate().is_ok());
    }

    #[test]
    fn config_rejects_negative_threshold() {
        let result = PowerConcentrationConfig::new(-0.1, 0.8, vec![], 168);
        assert!(result.is_err());
    }

    #[test]
    fn config_rejects_threshold_above_one() {
        let result = PowerConcentrationConfig::new(0.6, 1.5, vec![], 168);
        assert!(result.is_err());
    }

    #[test]
    fn config_rejects_critical_below_alert() {
        // alert = 0.6, critical = 0.5 → invalid.
        let result = PowerConcentrationConfig::new(0.6, 0.5, vec![], 168);
        assert!(result.is_err());
    }

    #[test]
    fn config_rejects_zero_interval() {
        let result = PowerConcentrationConfig::new(0.6, 0.8, vec![], 0);
        assert!(result.is_err());
    }

    #[test]
    fn config_validate_catches_bad_deserialized() {
        let config = PowerConcentrationConfig {
            alert_threshold: 0.5,
            critical_threshold: 0.3, // below alert
            factors_enabled: vec![],
            computation_interval_hours: 168,
        };
        assert!(config.validate().is_err());
    }

    // ── Serialization Round-trip ───────────────────────────────────────────

    #[test]
    fn index_serializes_and_deserializes() {
        let config = PowerConcentrationConfig::default();
        let index = PowerConcentrationComputer::compute(
            "roundtrip_test",
            &[vec!["member".into()], vec!["member".into()]],
            &["alice", "bob"],
            &[("alice", true)],
            &[("alice", 5), ("bob", 5)],
            &[0.2, 0.3],
            &config,
        );

        let json = serde_json::to_string(&index).expect("serialize");
        let deserialized: PowerConcentrationIndex =
            serde_json::from_str(&json).expect("deserialize");

        assert_eq!(index.community_id, deserialized.community_id);
        assert_eq!(index.score, deserialized.score);
        assert_eq!(index.factors, deserialized.factors);
        assert_eq!(index.alerts.len(), deserialized.alerts.len());
    }

    #[test]
    fn config_serializes_and_deserializes() {
        let config =
            PowerConcentrationConfig::new(0.7, 0.9, vec!["role_concentration".into()], 72)
                .expect("valid config");
        let json = serde_json::to_string(&config).expect("serialize");
        let deserialized: PowerConcentrationConfig =
            serde_json::from_str(&json).expect("deserialize");

        assert_eq!(config.alert_threshold, deserialized.alert_threshold);
        assert_eq!(config.critical_threshold, deserialized.critical_threshold);
        assert_eq!(config.factors_enabled, deserialized.factors_enabled);
        assert_eq!(
            config.computation_interval_hours,
            deserialized.computation_interval_hours
        );
    }

    // ── Edge Cases ─────────────────────────────────────────────────────────

    #[test]
    fn compute_with_empty_data() {
        let config = PowerConcentrationConfig::default();
        let index = PowerConcentrationComputer::compute(
            "empty_community",
            &[],
            &[],
            &[],
            &[],
            &[],
            &config,
        );
        assert_eq!(index.score, 0.0);
        assert!(index.alerts.is_empty());
    }

    #[test]
    fn compute_with_single_member() {
        let config = PowerConcentrationConfig::default();
        let index = PowerConcentrationComputer::compute(
            "solo",
            &[vec!["founder".into()]],
            &["alice"],
            &[("alice", true)],
            &[("alice", 10)],
            &[0.1],
            &config,
        );
        // Single member: role gini = 0 (only one person), proposal HHI = 1.0 (single entity),
        // decision = 1.0, info centrality = 1.0, exit = 0.1
        // Factors like HHI = 1.0 for single entity is expected.
        assert!(index.score > 0.0, "Single member should have some concentration");
    }

    #[test]
    fn score_is_always_in_range() {
        let config = PowerConcentrationConfig::default();

        // Worst case scenario.
        let index = PowerConcentrationComputer::compute(
            "extreme",
            &[
                vec!["a".into(), "b".into(), "c".into(), "d".into(), "e".into()],
                vec![],
                vec![],
            ],
            &["x", "x", "x", "x", "x"],
            &[("x", true), ("x", true), ("x", true)],
            &[("x", 999)],
            &[1.0, 1.0, 1.0],
            &config,
        );
        assert!(index.score >= 0.0 && index.score <= 1.0, "Score out of range: {}", index.score);

        // Best case scenario.
        let index2 = PowerConcentrationComputer::compute(
            "utopia",
            &[
                vec!["m".into()],
                vec!["m".into()],
                vec!["m".into()],
                vec!["m".into()],
            ],
            &["a", "b", "c", "d"],
            &[("a", true), ("b", true), ("c", true), ("d", true)],
            &[("a", 10), ("b", 10), ("c", 10), ("d", 10)],
            &[0.0, 0.0, 0.0, 0.0],
            &config,
        );
        assert!(index2.score >= 0.0 && index2.score <= 1.0, "Score out of range: {}", index2.score);
    }

    #[test]
    fn types_are_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<PowerConcentrationIndex>();
        assert_send_sync::<PowerFactors>();
        assert_send_sync::<PowerAlert>();
        assert_send_sync::<PowerConcentrationConfig>();
    }

    // ── Federation Scope ──────────────────────────────────────────────────

    fn make_index(community_id: &str, score: f64, has_alerts: bool) -> PowerConcentrationIndex {
        let alerts = if has_alerts {
            vec![PowerAlert {
                factor: "overall".into(),
                value: score,
                threshold: 0.6,
                description: "Test alert".into(),
                recommendation: "Test".into(),
            }]
        } else {
            vec![]
        };
        PowerConcentrationIndex {
            community_id: community_id.into(),
            score,
            factors: PowerFactors {
                role_concentration: score,
                proposal_dominance: 0.0,
                decision_influence: 0.0,
                information_centrality: 0.0,
                exit_barrier: 0.0,
            },
            alerts,
            computed_at: Utc::now(),
        }
    }

    #[test]
    fn filter_indices_scoped_unrestricted() {
        let indices = vec![
            make_index("alpha", 0.3, false),
            make_index("beta", 0.7, true),
        ];
        let filtered =
            PowerConcentrationComputer::filter_indices_scoped(&indices, &FederationScope::new());
        assert_eq!(filtered.len(), 2);
    }

    #[test]
    fn filter_indices_scoped_filters_communities() {
        let indices = vec![
            make_index("alpha", 0.3, false),
            make_index("beta", 0.7, true),
            make_index("gamma", 0.5, false),
        ];
        let scope = FederationScope::from_communities(["alpha", "gamma"]);
        let filtered = PowerConcentrationComputer::filter_indices_scoped(&indices, &scope);
        assert_eq!(filtered.len(), 2);
        assert_eq!(filtered[0].community_id, "alpha");
        assert_eq!(filtered[1].community_id, "gamma");
    }

    #[test]
    fn max_concentration_scoped() {
        let indices = vec![
            make_index("alpha", 0.3, false),
            make_index("beta", 0.9, true),
            make_index("gamma", 0.6, true),
        ];

        // Unrestricted: max is 0.9 (beta).
        let max =
            PowerConcentrationComputer::max_concentration_scoped(&indices, &FederationScope::new());
        assert!((max.unwrap() - 0.9).abs() < f64::EPSILON);

        // Scoped to alpha + gamma: max is 0.6 (gamma).
        let scope = FederationScope::from_communities(["alpha", "gamma"]);
        let max = PowerConcentrationComputer::max_concentration_scoped(&indices, &scope);
        assert!((max.unwrap() - 0.6).abs() < f64::EPSILON);
    }

    #[test]
    fn max_concentration_scoped_none_when_empty() {
        let indices: Vec<PowerConcentrationIndex> = vec![];
        assert!(
            PowerConcentrationComputer::max_concentration_scoped(&indices, &FederationScope::new())
                .is_none()
        );
    }

    #[test]
    fn communities_with_alerts_scoped() {
        let indices = vec![
            make_index("alpha", 0.3, false),
            make_index("beta", 0.7, true),
            make_index("gamma", 0.8, true),
            make_index("delta", 0.5, false),
        ];

        // Unrestricted: 2 communities with alerts (beta, gamma).
        assert_eq!(
            PowerConcentrationComputer::communities_with_alerts_scoped(
                &indices,
                &FederationScope::new()
            ),
            2
        );

        // Scoped to alpha + beta: 1 community with alerts (beta).
        let scope = FederationScope::from_communities(["alpha", "beta"]);
        assert_eq!(
            PowerConcentrationComputer::communities_with_alerts_scoped(&indices, &scope),
            1
        );

        // Scoped to alpha + delta: 0 communities with alerts.
        let scope = FederationScope::from_communities(["alpha", "delta"]);
        assert_eq!(
            PowerConcentrationComputer::communities_with_alerts_scoped(&indices, &scope),
            0
        );
    }
}
