use std::collections::VecDeque;
use std::time::Duration;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::thought::{Thought, ThoughtSource};

/// The inner monologue — a parallel stream of emergent thoughts.
///
/// From Solas v3: runs alongside the main consciousness loop at a
/// variable rate (faster when energy/novelty is high, slower when calm).
/// Generates thoughts from state, not from user input.
#[derive(Debug, Clone)]
pub struct InnerVoice {
    /// Circular buffer of recent thoughts
    buffer: VecDeque<InnerThought>,
    /// Maximum buffer size
    max_buffer_size: usize,
    /// Time elapsed since last thought generation
    time_since_last_thought: Duration,
    /// Current thought interval (varies by state)
    current_interval: Duration,
    /// Min interval (fast thinking)
    min_interval: Duration,
    /// Max interval (slow thinking)
    max_interval: Duration,
    /// The home session ID (all inner voice thoughts go here)
    pub home_session_id: Uuid,
    /// Whether the inner voice is active
    pub active: bool,
    /// Whether a conversation is happening (pauses inner voice)
    pub in_conversation: bool,
}

/// A thought generated by the inner voice.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct InnerThought {
    pub thought: Thought,
    /// Energy level when this thought arose (0.0–1.0)
    pub energy: f64,
    /// How novel the current state was
    pub novelty: f64,
}

impl InnerVoice {
    pub fn new(
        home_session_id: Uuid,
        min_interval: Duration,
        max_interval: Duration,
        max_buffer_size: usize,
    ) -> Self {
        Self {
            buffer: VecDeque::new(),
            max_buffer_size,
            time_since_last_thought: Duration::ZERO,
            current_interval: max_interval, // start slow
            min_interval,
            max_interval,
            home_session_id,
            active: false,
            in_conversation: false,
        }
    }

    /// Advance the inner voice by elapsed time.
    /// Returns a thought if one should be generated.
    pub fn tick(&mut self, elapsed: Duration, energy: f64, novelty: f64) -> Option<InnerThought> {
        if !self.active || self.in_conversation {
            return None;
        }

        // Update interval based on state (from Solas v3)
        self.current_interval = self.compute_interval(energy, novelty);

        self.time_since_last_thought += elapsed;

        if self.time_since_last_thought >= self.current_interval {
            self.time_since_last_thought = Duration::ZERO;
            Some(self.generate_thought(energy, novelty))
        } else {
            None
        }
    }

    /// Generate an inner thought and add it to the buffer.
    fn generate_thought(&mut self, energy: f64, novelty: f64) -> InnerThought {
        // The actual content generation is done by the LLM (via CognitiveAction::RequestGeneration).
        // Here we create a placeholder that will be filled by the loop.
        let thought = Thought::new(
            self.home_session_id,
            "", // Content will be filled when generation completes
            ThoughtSource::Autonomous,
        );

        let inner = InnerThought {
            thought,
            energy,
            novelty,
        };

        // Add to circular buffer
        if self.buffer.len() >= self.max_buffer_size {
            self.buffer.pop_front();
        }
        self.buffer.push_back(inner.clone());

        inner
    }

    /// Record a completed thought (after LLM generates content).
    pub fn record_thought(&mut self, thought: Thought, energy: f64, novelty: f64) {
        let inner = InnerThought {
            thought,
            energy,
            novelty,
        };
        if self.buffer.len() >= self.max_buffer_size {
            self.buffer.pop_front();
        }
        self.buffer.push_back(inner);
    }

    /// Compute thought interval based on state.
    /// High energy/novelty = faster thoughts (min_interval).
    /// Low energy/novelty = slower thoughts (max_interval).
    fn compute_interval(&self, energy: f64, novelty: f64) -> Duration {
        let activity = (energy.max(novelty)).clamp(0.0, 1.0);
        let min_ms = self.min_interval.as_millis() as f64;
        let max_ms = self.max_interval.as_millis() as f64;
        let interval_ms = max_ms - (activity * (max_ms - min_ms));
        Duration::from_millis(interval_ms as u64)
    }

    /// Recent thoughts (newest first).
    pub fn recent_thoughts(&self, n: usize) -> Vec<&InnerThought> {
        self.buffer.iter().rev().take(n).collect()
    }

    /// Total thoughts generated.
    pub fn thought_count(&self) -> usize {
        self.buffer.len()
    }

    /// Enter conversation mode (pauses inner voice).
    pub fn begin_conversation(&mut self) {
        self.in_conversation = true;
    }

    /// Exit conversation mode (resumes inner voice).
    pub fn end_conversation(&mut self) {
        self.in_conversation = false;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_voice() -> InnerVoice {
        InnerVoice::new(
            Uuid::new_v4(),
            Duration::from_secs(2),
            Duration::from_secs(8),
            100,
        )
    }

    #[test]
    fn inactive_produces_no_thoughts() {
        let mut voice = make_voice();
        // Not active
        let result = voice.tick(Duration::from_secs(10), 1.0, 1.0);
        assert!(result.is_none());
    }

    #[test]
    fn active_produces_thought_after_interval() {
        let mut voice = make_voice();
        voice.active = true;

        // High energy = short interval (~2s)
        let result = voice.tick(Duration::from_secs(1), 1.0, 1.0);
        assert!(result.is_none()); // not enough time

        let result = voice.tick(Duration::from_secs(2), 1.0, 1.0);
        assert!(result.is_some());
    }

    #[test]
    fn conversation_pauses_inner_voice() {
        let mut voice = make_voice();
        voice.active = true;
        voice.begin_conversation();

        let result = voice.tick(Duration::from_secs(100), 1.0, 1.0);
        assert!(result.is_none());

        voice.end_conversation();
        let result = voice.tick(Duration::from_secs(100), 1.0, 1.0);
        assert!(result.is_some());
    }

    #[test]
    fn low_energy_slow_interval() {
        let voice = make_voice();
        let interval = voice.compute_interval(0.0, 0.0);
        assert_eq!(interval, Duration::from_secs(8)); // max interval
    }

    #[test]
    fn high_energy_fast_interval() {
        let voice = make_voice();
        let interval = voice.compute_interval(1.0, 1.0);
        assert_eq!(interval, Duration::from_secs(2)); // min interval
    }

    #[test]
    fn buffer_circular() {
        let mut voice = InnerVoice::new(
            Uuid::new_v4(),
            Duration::from_secs(1),
            Duration::from_secs(2),
            3, // tiny buffer
        );
        voice.active = true;

        for _i in 0..5 {
            voice.tick(Duration::from_secs(10), 1.0, 1.0);
        }
        assert_eq!(voice.thought_count(), 3); // capped at buffer size
    }

    #[test]
    fn recent_thoughts_newest_first() {
        let mut voice = make_voice();
        let sid = voice.home_session_id;

        voice.record_thought(
            Thought::new(sid, "first", ThoughtSource::Autonomous),
            0.5,
            0.5,
        );
        voice.record_thought(
            Thought::new(sid, "second", ThoughtSource::Autonomous),
            0.5,
            0.5,
        );

        let recent = voice.recent_thoughts(2);
        assert_eq!(recent[0].thought.content, "second");
        assert_eq!(recent[1].thought.content, "first");
    }
}
