//! React code projection — maps DigitRenderers to React components + CSS.
//!
//! Generates React (JSX/TSX) components with CSS. Regalia formations map
//! to flexbox layout (Rank -> flex-row, Column -> flex-column, etc.).


use ideas::Digit;
use regalia::FormationKind;

use super::builder::CodeBuilder;
use super::context::ProjectionContext;
use super::name_resolver::NameResolver;
use super::{CodeProjection, GeneratedFile};
use crate::error::MagicError;

/// React code projection target.
///
/// Generates TSX (TypeScript JSX) components with companion CSS modules.
/// Formations map to CSS flexbox. Regalia tokens map to CSS custom properties.
pub struct ReactProjection;

impl CodeProjection for ReactProjection {
    fn name(&self) -> &str {
        "React"
    }

    fn file_extension(&self) -> &str {
        "tsx"
    }

    fn project(
        &self,
        context: &ProjectionContext,
    ) -> Result<Vec<GeneratedFile>, MagicError> {
        let mut files = Vec::new();
        let mut resolver = NameResolver::new();

        for &root_id in &context.root_ids {
            if let Some(digit) = context.digit(root_id) {
                let component_name = resolver.type_name(
                    &digit_display_name(digit),
                );
                let mut builder = CodeBuilder::new();
                let mut css_builder = CodeBuilder::new();

                // TSX file
                builder.comment("Generated by Magic — Omnidea");
                builder.comment("Do not edit manually. Changes will be overwritten.");
                builder.blank();
                builder.line("import React from 'react';");
                builder.line(format!("import styles from './{component_name}.module.css';"));
                builder.blank();

                builder.braced(
                    format!("export const {component_name}: React.FC = () =>"),
                    |b| {
                        b.line("return (");
                        b.indent(|b| {
                            emit_digit_jsx(b, digit, context, &mut css_builder, &mut resolver);
                        });
                        b.line(");");
                    },
                );
                builder.blank();
                builder.line(format!("export default {component_name};"));

                files.push(GeneratedFile::text(
                    format!("{component_name}.tsx"),
                    builder.output(),
                ));

                // CSS module
                if !css_builder.is_empty() {
                    css_builder.line("/* Generated by Magic — Omnidea */");
                    files.push(GeneratedFile::text(
                        format!("{component_name}.module.css"),
                        css_builder.output(),
                    ));
                }
            }
        }

        Ok(files)
    }
}

/// Emit JSX for a single digit and its children.
fn emit_digit_jsx(
    builder: &mut CodeBuilder,
    digit: &Digit,
    context: &ProjectionContext,
    css: &mut CodeBuilder,
    resolver: &mut NameResolver,
) {
    let children = context.children_of(digit.id());

    if !children.is_empty() {
        let formation = context.formation_for(digit.id());
        let css_class = emit_formation_css(css, formation, digit, resolver);

        builder.line(format!("<div className={{styles.{css_class}}}>"));
        builder.indent(|b| {
            for &child_id in children {
                if let Some(child) = context.digit(child_id) {
                    emit_digit_jsx(b, child, context, css, resolver);
                }
            }
        });
        builder.line("</div>");
    } else {
        emit_leaf_jsx(builder, digit);
    }
}

/// Emit CSS for a formation and return the class name.
fn emit_formation_css(
    css: &mut CodeBuilder,
    formation: Option<&FormationKind>,
    digit: &Digit,
    resolver: &mut NameResolver,
) -> String {
    let class_name = resolver.property_name(&format!("{}-container", digit.digit_type().replace('.', "-")));

    let direction = match formation {
        Some(FormationKind::Rank { .. }) => "row",
        Some(FormationKind::Tier) => "row", // ZStack doesn't have direct CSS equivalent
        _ => "column",
    };

    let spacing = digit.properties.get("spacing")
        .and_then(|v| v.as_double())
        .unwrap_or(8.0);

    css.braced(format!(".{class_name}"), |c| {
        c.line("display: flex;");
        c.line(format!("flex-direction: {direction};"));
        c.line(format!("gap: {spacing}px;"));

        if let Some(padding) = digit.properties.get("padding").and_then(|v| v.as_double()) {
            c.line(format!("padding: {padding}px;"));
        }

        if matches!(formation, Some(FormationKind::Procession { .. })) {
            c.line("flex-wrap: wrap;");
        }

        if matches!(formation, Some(FormationKind::Tier)) {
            c.line("position: relative;");
        }
    });
    css.blank();

    class_name
}

/// Emit JSX for a leaf digit.
fn emit_leaf_jsx(builder: &mut CodeBuilder, digit: &Digit) {
    match digit.digit_type() {
        "text" | "text.paragraph" => {
            let text = digit_text_content(digit);
            let escaped = escape_jsx(&text);
            builder.line(format!("<p>{escaped}</p>"));
        }
        "text.heading" => {
            let text = digit.properties.get("text")
                .and_then(|v| v.as_str())
                .unwrap_or("Heading");
            let level = digit.properties.get("level")
                .and_then(|v| v.as_int())
                .unwrap_or(1)
                .min(6);
            let escaped = escape_jsx(text);
            builder.line(format!("<h{level}>{escaped}</h{level}>"));
        }
        "image" => {
            let alt = digit.properties.get("alt")
                .and_then(|v| v.as_str())
                .unwrap_or("Image");
            let escaped_alt = escape_jsx(alt);
            builder.line(format!("<img src=\"\" alt=\"{escaped_alt}\" />"));
        }
        "code" | "text.code" => {
            let code = digit.properties.get("code")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let language = digit.properties.get("language")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let escaped = escape_jsx(code);
            builder.line(format!("<pre><code className=\"language-{language}\">{escaped}</code></pre>"));
        }
        "divider" => {
            builder.line("<hr />");
        }
        "link" => {
            let text = digit_text_content(digit);
            let url = digit.properties.get("url")
                .and_then(|v| v.as_str())
                .unwrap_or("#");
            let escaped_text = escape_jsx(&text);
            let escaped_url = escape_jsx(url);
            builder.line(format!("<a href=\"{escaped_url}\">{escaped_text}</a>"));
        }
        "interactive.button" => {
            let label = digit.properties.get("label")
                .and_then(|v| v.as_str())
                .unwrap_or("Button");
            let style = digit.properties.get("style")
                .and_then(|v| v.as_str())
                .unwrap_or("primary");
            let escaped = escape_jsx(label);
            builder.line(format!("<button className=\"btn btn-{style}\">{escaped}</button>"));
        }
        "text.list" => {
            let style = digit.properties.get("style")
                .and_then(|v| v.as_str())
                .unwrap_or("unordered");
            let items: Vec<String> = digit.properties.get("items")
                .and_then(|v| {
                    if let x::Value::Array(arr) = v {
                        Some(arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
                    } else {
                        None
                    }
                })
                .unwrap_or_default();

            let tag = if style == "ordered" { "ol" } else { "ul" };
            builder.line(format!("<{tag}>"));
            builder.indent(|b| {
                for item in &items {
                    let escaped = escape_jsx(item);
                    b.line(format!("<li>{escaped}</li>"));
                }
            });
            builder.line(format!("</{tag}>"));
        }
        "text.blockquote" => {
            let text = digit.properties.get("text")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let escaped = escape_jsx(text);
            builder.line(format!("<blockquote>{escaped}</blockquote>"));
        }
        "text.callout" => {
            let text = digit.properties.get("text")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let style = digit.properties.get("style")
                .and_then(|v| v.as_str())
                .unwrap_or("info");
            let escaped = escape_jsx(text);
            let role = if style == "warning" || style == "error" { " role=\"alert\"" } else { "" };
            builder.line(format!("<div className=\"callout callout-{style}\"{role}>{escaped}</div>"));
        }
        _ => {
            let dtype = digit.digit_type();
            builder.line(format!("{{/* TODO: Implement {dtype} */}}"));
            builder.line(format!("<div className=\"unknown\">[{dtype}]</div>"));
        }
    }
}

fn escape_jsx(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('{', "&#123;")
        .replace('}', "&#125;")
}

fn digit_display_name(digit: &Digit) -> String {
    digit.properties.get("title")
        .or(digit.properties.get("name"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| format!("{}-component", digit.digit_type().replace('.', "-")))
}

fn digit_text_content(digit: &Digit) -> String {
    if let Some(s) = digit.content.as_str() { return s.to_string(); }
    if let Some(s) = digit.properties.get("text").and_then(|v| v.as_str()) { return s.to_string(); }
    if let Some(s) = digit.properties.get("label").and_then(|v| v.as_str()) { return s.to_string(); }
    String::new()
}

#[cfg(test)]
mod tests {
    use super::*;
    use ideas::Digit;
    use regalia::Reign;
    use uuid::Uuid;
    use x::Value;

    fn make_digit(dtype: &str) -> Digit {
        Digit::new(dtype.into(), Value::Null, "cpub1test".into()).unwrap()
    }

    fn simple_context(digits: &[Digit], root_id: Option<Uuid>) -> ProjectionContext {
        ProjectionContext::build(digits, root_id, Reign::default())
    }

    #[test]
    fn projects_single_text() {
        let digit = make_digit("text")
            .with_content(Value::from("Hello"), "test");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = ReactProjection;
        let files = proj.project(&ctx).unwrap();

        assert!(!files.is_empty());
        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("import React"));
        assert!(content.contains("<p>Hello</p>"));
    }

    #[test]
    fn projects_heading_h2() {
        let digit = make_digit("text.heading")
            .with_property("text".into(), Value::from("Section"), "test")
            .with_property("level".into(), Value::Int(2), "test");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = ReactProjection;
        let files = proj.project(&ctx).unwrap();

        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("<h2>Section</h2>"));
    }

    #[test]
    fn name_and_extension() {
        let proj = ReactProjection;
        assert_eq!(proj.name(), "React");
        assert_eq!(proj.file_extension(), "tsx");
    }

    #[test]
    fn escapes_html_entities() {
        let text = "A < B & C > D";
        let escaped = escape_jsx(text);
        assert!(escaped.contains("&lt;"));
        assert!(escaped.contains("&amp;"));
        assert!(escaped.contains("&gt;"));
    }
}
