//! SwiftUI code projection — maps DigitRenderers to SwiftUI view code.
//!
//! Primary projection target for Apple platforms. Reads the `ProjectionContext`
//! and emits well-formed SwiftUI source files. Regalia formations map 1:1 to
//! SwiftUI layout primitives (Rank -> HStack, Column -> VStack, etc.).


use ideas::Digit;
use regalia::FormationKind;

use super::builder::CodeBuilder;
use super::context::ProjectionContext;
use super::name_resolver::NameResolver;
use super::{CodeProjection, GeneratedFile};
use crate::error::MagicError;

/// SwiftUI code projection target.
///
/// Generates SwiftUI view code from the projection context. Each root digit
/// becomes a top-level SwiftUI View struct. Formations map to SwiftUI
/// layout containers. Regalia tokens map to SwiftUI modifiers.
pub struct SwiftUIProjection;

impl CodeProjection for SwiftUIProjection {
    fn name(&self) -> &str {
        "SwiftUI"
    }

    fn file_extension(&self) -> &str {
        "swift"
    }

    fn project(
        &self,
        context: &ProjectionContext,
    ) -> Result<Vec<GeneratedFile>, MagicError> {
        let mut files = Vec::new();
        let mut resolver = NameResolver::with_swift_reserved();

        for &root_id in &context.root_ids {
            if let Some(digit) = context.digit(root_id) {
                let type_name = resolver.type_name(
                    &digit_display_name(digit),
                );
                let mut builder = CodeBuilder::new();

                // File header
                builder.comment("Generated by Magic — Omnidea");
                builder.comment("Do not edit manually. Changes will be overwritten.");
                builder.blank();
                builder.line("import SwiftUI");
                builder.blank();

                // View struct
                builder.braced(format!("struct {type_name}: View"), |b| {
                    b.braced("var body: some View", |b| {
                        emit_digit(b, digit, context, &mut resolver);
                    });
                });

                let filename = format!("{type_name}.swift");
                files.push(GeneratedFile::text(filename, builder.output()));
            }
        }

        Ok(files)
    }
}

/// Emit SwiftUI code for a single digit and its children.
fn emit_digit(
    builder: &mut CodeBuilder,
    digit: &Digit,
    context: &ProjectionContext,
    resolver: &mut NameResolver,
) {
    let children = context.children_of(digit.id());

    if !children.is_empty() {
        // This is a container with children — use formation
        let formation = context.formation_for(digit.id());
        emit_formation_open(builder, formation, digit);

        builder.indent(|b| {
            for &child_id in children {
                if let Some(child) = context.digit(child_id) {
                    emit_digit(b, child, context, resolver);
                }
            }
        });

        emit_formation_close(builder, digit);
    } else {
        // Leaf digit
        emit_leaf(builder, digit, resolver);
    }

    // Apply accessibility modifiers
    emit_accessibility(builder, digit);
}

/// Emit the opening of a formation container.
fn emit_formation_open(builder: &mut CodeBuilder, formation: Option<&FormationKind>, digit: &Digit) {
    let spacing = digit.properties.get("spacing")
        .and_then(|v| v.as_double())
        .map(|s| format!(", spacing: {s}"))
        .unwrap_or_default();

    match formation {
        Some(FormationKind::Rank { .. }) => {
            builder.line(format!("HStack(alignment: .center{spacing}) {{"));
        }
        Some(FormationKind::Column { .. }) => {
            builder.line(format!("VStack(alignment: .leading{spacing}) {{"));
        }
        Some(FormationKind::Tier) => {
            builder.line("ZStack {");
        }
        Some(FormationKind::Procession { .. }) => {
            builder.line("ScrollView {");
        }
        Some(FormationKind::OpenCourt) => {
            builder.line("ZStack { // OpenCourt (absolute positioning)");
        }
        Some(FormationKind::Custom(name)) => {
            builder.comment(format!("Custom formation: {name}"));
            builder.line("VStack {");
        }
        None => {
            // Default: VStack
            builder.line("VStack {");
        }
    }
}

/// Emit the closing of a formation container.
fn emit_formation_close(builder: &mut CodeBuilder, digit: &Digit) {
    // Close the container and apply container-level modifiers
    let mut closing = "}".to_string();

    if let Some(padding) = digit.properties.get("padding").and_then(|v| v.as_double()) {
        closing.push_str(&format!("\n.padding({padding})"));
    }
    if let Some(bg) = digit.properties.get("background").and_then(|v| v.as_str()) {
        closing.push_str(&format!("\n.background(Color(\"{bg}\"))"));
    }

    builder.line(closing);
}

/// Emit a leaf digit as SwiftUI.
fn emit_leaf(builder: &mut CodeBuilder, digit: &Digit, _resolver: &mut NameResolver) {
    match digit.digit_type() {
        "text" | "text.paragraph" => {
            let text = digit_text_content(digit);
            let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
            let mut line = format!("Text(\"{escaped}\")");

            if let Some(font_size) = digit.properties.get("font_size").and_then(|v| v.as_double()) {
                line.push_str(&format!("\n    .font(.system(size: {font_size}))"));
            }
            if let Some(weight) = digit.properties.get("font_weight").and_then(|v| v.as_str()) {
                line.push_str(&format!("\n    .fontWeight(.{weight})"));
            }
            if let Some(alignment) = digit.properties.get("alignment").and_then(|v| v.as_str()) {
                let frame_align = match alignment {
                    "center" => "center",
                    "trailing" | "right" => "trailing",
                    _ => "leading",
                };
                line.push_str(&format!("\n    .frame(maxWidth: .infinity, alignment: .{frame_align})"));
            }

            builder.line(line);
        }
        "text.heading" => {
            let text = digit.properties.get("text")
                .and_then(|v| v.as_str())
                .unwrap_or("Heading");
            let level = digit.properties.get("level")
                .and_then(|v| v.as_int())
                .unwrap_or(1);
            let font = match level {
                1 => "largeTitle",
                2 => "title",
                3 => "title2",
                4 => "title3",
                5 => "headline",
                _ => "subheadline",
            };
            let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
            builder.line(format!("Text(\"{escaped}\")\n    .font(.{font})\n    .fontWeight(.bold)"));
        }
        "image" => {
            let alt = digit.properties.get("alt")
                .and_then(|v| v.as_str())
                .unwrap_or("Image");
            let fit_mode = digit.properties.get("fit_mode")
                .and_then(|v| v.as_str())
                .unwrap_or("fit");
            let aspect = if fit_mode == "fill" { "fill" } else { "fit" };
            let escaped_alt = alt.replace('\\', "\\\\").replace('"', "\\\"");

            let mut line = format!("Image(systemName: \"photo\")\n    .resizable()\n    .aspect{}",
                if aspect == "fill" { "Ratio(contentMode: .fill)" } else { "Ratio(contentMode: .fit)" });
            line.push_str(&format!("\n    .accessibilityLabel(\"{escaped_alt}\")"));

            if let Some(w) = digit.properties.get("width").and_then(|v| v.as_double()) {
                if let Some(h) = digit.properties.get("height").and_then(|v| v.as_double()) {
                    line.push_str(&format!("\n    .frame(width: {w}, height: {h})"));
                }
            }

            builder.line(line);
        }
        "code" | "text.code" => {
            let code = digit.properties.get("code")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let escaped = code.replace('\\', "\\\\").replace('"', "\\\"");
            builder.line(format!("Text(\"{escaped}\")\n    .font(.system(.body, design: .monospaced))\n    .padding()\n    .background(Color(.systemGray6))\n    .cornerRadius(8)"));
        }
        "divider" => {
            builder.line("Divider()");
        }
        "link" => {
            let text = digit_text_content(digit);
            let url = digit.properties.get("url")
                .and_then(|v| v.as_str())
                .unwrap_or("#");
            let escaped_text = text.replace('\\', "\\\\").replace('"', "\\\"");
            let escaped_url = url.replace('\\', "\\\\").replace('"', "\\\"");
            builder.line(format!("Link(\"{escaped_text}\", destination: URL(string: \"{escaped_url}\")!)"));
        }
        "interactive.button" => {
            let label = digit.properties.get("label")
                .and_then(|v| v.as_str())
                .unwrap_or("Button");
            let style = digit.properties.get("style")
                .and_then(|v| v.as_str())
                .unwrap_or("primary");
            let escaped = label.replace('\\', "\\\\").replace('"', "\\\"");
            let style_modifier = match style {
                "primary" => ".buttonStyle(.borderedProminent)",
                "secondary" => ".buttonStyle(.bordered)",
                "tertiary" => ".buttonStyle(.borderless)",
                "danger" => ".buttonStyle(.borderedProminent)\n    .tint(.red)",
                _ => ".buttonStyle(.bordered)",
            };
            builder.line(format!("Button(\"{escaped}\") {{\n    // Action\n}}\n{style_modifier}"));
        }
        "text.list" => {
            let style = digit.properties.get("style")
                .and_then(|v| v.as_str())
                .unwrap_or("unordered");
            let items: Vec<String> = digit.properties.get("items")
                .and_then(|v| {
                    if let x::Value::Array(arr) = v {
                        Some(arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
                    } else {
                        None
                    }
                })
                .unwrap_or_default();

            if style == "ordered" {
                builder.braced("List", |b| {
                    for (i, item) in items.iter().enumerate() {
                        let escaped = item.replace('\\', "\\\\").replace('"', "\\\"");
                        b.line(format!("Text(\"{}.  {escaped}\")", i + 1));
                    }
                });
            } else {
                builder.braced("List", |b| {
                    for item in &items {
                        let escaped = item.replace('\\', "\\\\").replace('"', "\\\"");
                        b.line(format!("Text(\"{escaped}\")"));
                    }
                });
            }
        }
        "text.blockquote" => {
            let text = digit.properties.get("text")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
            builder.braced("HStack", |b| {
                b.line("Rectangle()\n    .fill(Color.secondary)\n    .frame(width: 4)");
                b.line(format!("Text(\"{escaped}\")\n    .italic()\n    .foregroundStyle(.secondary)"));
            });
        }
        "text.callout" => {
            let text = digit.properties.get("text")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let style = digit.properties.get("style")
                .and_then(|v| v.as_str())
                .unwrap_or("info");
            let color = match style {
                "warning" => "Color.orange",
                "error" => "Color.red",
                "success" => "Color.green",
                _ => "Color.blue",
            };
            let escaped = text.replace('\\', "\\\\").replace('"', "\\\"");
            builder.line(format!("Text(\"{escaped}\")\n    .padding()\n    .background({color}.opacity(0.1))\n    .cornerRadius(8)"));
        }
        _ => {
            // Unknown type — emit placeholder
            let dtype = digit.digit_type();
            builder.comment(format!("TODO: Implement projection for {dtype}"));
            builder.line(format!("Text(\"[{dtype}]\")\n    .foregroundStyle(.secondary)"));
        }
    }
}

/// Emit SwiftUI accessibility modifiers for a digit.
fn emit_accessibility(builder: &mut CodeBuilder, digit: &Digit) {
    if let Some(meta) = digit.accessibility() {
        let escaped_label = meta.label.replace('\\', "\\\\").replace('"', "\\\"");

        // Only emit if there's meaningful accessibility metadata
        builder.line(format!(".accessibilityLabel(\"{escaped_label}\")"));

        if let Some(ref hint) = meta.hint {
            let escaped = hint.replace('\\', "\\\\").replace('"', "\\\"");
            builder.line(format!(".accessibilityHint(\"{escaped}\")"));
        }
        if let Some(ref value) = meta.value {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
            builder.line(format!(".accessibilityValue(\"{escaped}\")"));
        }
    }
}

/// Get a display name for a digit (for struct naming).
fn digit_display_name(digit: &Digit) -> String {
    digit.properties.get("title")
        .or(digit.properties.get("name"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| {
            format!("{}-view", digit.digit_type().replace('.', "-"))
        })
}

/// Extract text content from a digit.
fn digit_text_content(digit: &Digit) -> String {
    if let Some(s) = digit.content.as_str() {
        return s.to_string();
    }
    if let Some(s) = digit.properties.get("text").and_then(|v| v.as_str()) {
        return s.to_string();
    }
    if let Some(s) = digit.properties.get("label").and_then(|v| v.as_str()) {
        return s.to_string();
    }
    String::new()
}

#[cfg(test)]
mod tests {
    use super::*;
    use ideas::Digit;
    use regalia::Reign;
    use uuid::Uuid;
    use x::Value;

    fn make_digit(dtype: &str) -> Digit {
        Digit::new(dtype.into(), Value::Null, "cpub1test".into()).unwrap()
    }

    fn simple_context(digits: &[Digit], root_id: Option<Uuid>) -> ProjectionContext {
        ProjectionContext::build(digits, root_id, Reign::default())
    }

    #[test]
    fn projects_empty_context() {
        let ctx = simple_context(&[], None);
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();
        assert!(files.is_empty());
    }

    #[test]
    fn projects_single_text() {
        let digit = make_digit("text")
            .with_content(Value::from("Hello"), "test");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();

        assert_eq!(files.len(), 1);
        assert!(files[0].relative_path.ends_with(".swift"));
        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("import SwiftUI"));
        assert!(content.contains("Text(\"Hello\")"));
        assert!(content.contains("struct"));
        assert!(content.contains("var body: some View"));
    }

    #[test]
    fn projects_container_with_children() {
        let container = make_digit("container")
            .with_property("formation".into(), Value::from("rank"), "test");
        let child1 = make_digit("text")
            .with_content(Value::from("A"), "test");
        let child2 = make_digit("text")
            .with_content(Value::from("B"), "test");
        let container = container.with_child(child1.id(), "test").with_child(child2.id(), "test");
        let cid = container.id();

        let ctx = simple_context(&[container, child1, child2], Some(cid));
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();

        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("HStack"));
        assert!(content.contains("Text(\"A\")"));
        assert!(content.contains("Text(\"B\")"));
    }

    #[test]
    fn projects_heading() {
        let digit = make_digit("text.heading")
            .with_property("text".into(), Value::from("Title"), "test")
            .with_property("level".into(), Value::Int(1), "test");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();

        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains(".largeTitle"));
        assert!(content.contains("Title"));
    }

    #[test]
    fn projects_button() {
        let digit = make_digit("interactive.button")
            .with_property("label".into(), Value::from("Save"), "test")
            .with_property("style".into(), Value::from("primary"), "test");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();

        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("Button(\"Save\")"));
        assert!(content.contains(".borderedProminent"));
    }

    #[test]
    fn projects_divider() {
        let digit = make_digit("divider");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();

        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("Divider()"));
    }

    #[test]
    fn name_and_extension() {
        let proj = SwiftUIProjection;
        assert_eq!(proj.name(), "SwiftUI");
        assert_eq!(proj.file_extension(), "swift");
    }

    #[test]
    fn code_projection_is_object_safe() {
        fn _accepts(_: &dyn CodeProjection) {}
        _accepts(&SwiftUIProjection);
    }

    #[test]
    fn escapes_special_characters() {
        let digit = make_digit("text")
            .with_content(Value::from("He said \"hello\""), "test");
        let id = digit.id();
        let ctx = simple_context(&[digit], Some(id));
        let proj = SwiftUIProjection;
        let files = proj.project(&ctx).unwrap();

        let content = match &files[0].contents {
            super::super::FileContents::Text(s) => s,
            _ => panic!("expected text"),
        };
        assert!(content.contains("\\\"hello\\\""));
    }
}
