use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::balance::Ledger;
use crate::policy::FortunePolicy;
use crate::treasury::{ReceiveReason, Treasury};

/// Demurrage engine — compound daily decay on liquid balances.
///
/// From Consortium Art. 2 §3: "Surplus generated by a Consortium shall be
/// reinvested in the Commons or equitably distributed among its contributors.
/// Wealth that is hoarded, hidden, or extracted without restoration shall be
/// regarded as unlawful."
///
/// Demurrage feeds UBI: decayed Cool returns to treasury for redistribution.
/// Only liquid Cool decays — locked Cool (backing Cash) is exempt.
/// Balances at or below the exemption floor are exempt (protects the poorest).
///
/// Formula: decay = balance - balance × (1 - daily_rate)^days
/// where daily_rate = monthly_rate / 30
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DemurrageEngine {
    pub total_decayed: i64,
    pub cycles_completed: u64,
}

impl DemurrageEngine {
    /// Create a new demurrage engine with no history.
    pub fn new() -> Self {
        Self {
            total_decayed: 0,
            cycles_completed: 0,
        }
    }

    /// Calculate decay for a given balance over a number of days.
    ///
    /// Uses compound formula: remaining = balance × (1 - daily_rate)^days
    /// Exempt if balance <= floor.
    pub fn calculate_decay(&self, balance: i64, days: u32, policy: &FortunePolicy) -> i64 {
        if balance <= policy.demurrage_exemption_floor {
            return 0;
        }
        if days == 0 {
            return 0;
        }

        let daily_rate = policy.daily_demurrage_rate();
        let retention = (1.0 - daily_rate).powi(days as i32);
        let remaining = (balance as f64) * retention;
        let decay = (balance as f64) - remaining;

        decay.round() as i64
    }

    /// Preview what demurrage would look like for an account.
    pub fn preview(
        &self,
        pubkey: &str,
        ledger: &Ledger,
        policy: &FortunePolicy,
    ) -> DemurragePreview {
        let balance = ledger.balance(pubkey);
        let days = days_since(balance.last_demurrage);
        let decay = self.calculate_decay(balance.liquid, days, policy);

        DemurragePreview {
            pubkey: pubkey.into(),
            current_balance: balance.liquid,
            locked_balance: balance.locked,
            days_since_last_demurrage: days,
            decay_amount: decay,
            balance_after: balance.liquid - decay,
            demurrage_rate: policy.demurrage_rate,
            exemption_floor: policy.demurrage_exemption_floor,
        }
    }

    /// Apply demurrage to a single account.
    pub fn apply(
        &mut self,
        pubkey: &str,
        ledger: &mut Ledger,
        treasury: &mut Treasury,
        policy: &FortunePolicy,
    ) -> i64 {
        let balance = ledger.balance(pubkey);

        // Skip if below exemption floor
        if balance.liquid <= policy.demurrage_exemption_floor {
            ledger.update_demurrage_timestamp(pubkey);
            return 0;
        }

        let days = days_since(balance.last_demurrage);
        if days == 0 {
            return 0;
        }

        let decay = self.calculate_decay(balance.liquid, days, policy);
        if decay > 0 {
            let actual = ledger.apply_demurrage(pubkey, decay);
            treasury.receive(actual, ReceiveReason::Demurrage);
            self.total_decayed += actual;
            actual
        } else {
            0
        }
    }

    /// Run a full demurrage cycle across all accounts.
    pub fn run_cycle(
        &mut self,
        ledger: &mut Ledger,
        treasury: &mut Treasury,
        policy: &FortunePolicy,
    ) -> DemurrageCycleResult {
        let started_at = Utc::now();
        let accounts: Vec<String> = ledger
            .all_accounts()
            .iter()
            .map(|(k, _)| k.to_string())
            .collect();

        let mut accounts_processed = 0u32;
        let mut accounts_decayed = 0u32;
        let mut total_decayed_this_cycle: i64 = 0;

        for pubkey in &accounts {
            let decayed = self.apply(pubkey, ledger, treasury, policy);
            accounts_processed += 1;
            if decayed > 0 {
                accounts_decayed += 1;
                total_decayed_this_cycle += decayed;
            }
        }

        self.cycles_completed += 1;

        DemurrageCycleResult {
            cycle_number: self.cycles_completed,
            started_at,
            completed_at: Utc::now(),
            accounts_processed,
            accounts_decayed,
            total_decayed: total_decayed_this_cycle,
        }
    }
}

impl Default for DemurrageEngine {
    fn default() -> Self {
        Self::new()
    }
}

/// Preview of demurrage for a single account.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DemurragePreview {
    pub pubkey: String,
    pub current_balance: i64,
    pub locked_balance: i64,
    pub days_since_last_demurrage: u32,
    pub decay_amount: i64,
    pub balance_after: i64,
    pub demurrage_rate: f64,
    pub exemption_floor: i64,
}

impl DemurragePreview {
    /// Whether this account is exempt from demurrage (balance at or below floor).
    pub fn is_exempt(&self) -> bool {
        self.current_balance <= self.exemption_floor
    }

    /// The decay amount as a percentage of the current balance.
    pub fn decay_percentage(&self) -> f64 {
        if self.current_balance == 0 {
            return 0.0;
        }
        (self.decay_amount as f64 / self.current_balance as f64) * 100.0
    }
}

/// Result of a full demurrage cycle.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DemurrageCycleResult {
    pub cycle_number: u64,
    pub started_at: DateTime<Utc>,
    pub completed_at: DateTime<Utc>,
    pub accounts_processed: u32,
    pub accounts_decayed: u32,
    pub total_decayed: i64,
}

impl DemurrageCycleResult {
    /// Percentage of accounts that had Cool decayed in this cycle.
    pub fn decay_rate_percent(&self) -> f64 {
        if self.accounts_processed == 0 {
            return 0.0;
        }
        (self.accounts_decayed as f64 / self.accounts_processed as f64) * 100.0
    }
}

/// Calculate days since a given timestamp.
fn days_since(timestamp: DateTime<Utc>) -> u32 {
    let elapsed = Utc::now().signed_duration_since(timestamp);
    elapsed.num_days().max(0) as u32
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::treasury::NetworkMetrics;

    fn test_policy() -> FortunePolicy {
        FortunePolicy::default_policy()
    }

    fn test_treasury(policy: &FortunePolicy) -> Treasury {
        let mut t = Treasury::new(policy.clone());
        t.update_metrics(NetworkMetrics {
            active_users: 1000,
            total_ideas: 0,
            total_collectives: 0,
        });
        t
    }

    #[test]
    fn decay_formula_30_days() {
        let engine = DemurrageEngine::new();
        let policy = test_policy();
        // 1000 Cool, 30 days, 3% monthly
        let decay = engine.calculate_decay(1000, 30, &policy);
        // Compound: 1000 * (1 - (1 - 0.001)^30) ≈ 29.6
        assert!((29..=31).contains(&decay), "decay was {decay}");
    }

    #[test]
    fn decay_formula_1_day() {
        let engine = DemurrageEngine::new();
        let policy = test_policy();
        // 10000 Cool, 1 day
        let decay = engine.calculate_decay(10_000, 1, &policy);
        // 10000 * 0.001 = 10
        assert_eq!(decay, 10);
    }

    #[test]
    fn decay_exemption_floor() {
        let engine = DemurrageEngine::new();
        let policy = test_policy();
        // Balance at or below floor = 0 decay
        assert_eq!(engine.calculate_decay(10, 30, &policy), 0);
        assert_eq!(engine.calculate_decay(5, 30, &policy), 0);
    }

    #[test]
    fn decay_zero_days() {
        let engine = DemurrageEngine::new();
        let policy = test_policy();
        assert_eq!(engine.calculate_decay(1000, 0, &policy), 0);
    }

    #[test]
    fn decay_increases_with_time() {
        let engine = DemurrageEngine::new();
        let policy = test_policy();
        let d1 = engine.calculate_decay(1000, 1, &policy);
        let d7 = engine.calculate_decay(1000, 7, &policy);
        let d30 = engine.calculate_decay(1000, 30, &policy);
        assert!(d1 < d7);
        assert!(d7 < d30);
    }

    #[test]
    fn decay_scales_with_balance() {
        let engine = DemurrageEngine::new();
        let policy = test_policy();
        let small = engine.calculate_decay(100, 30, &policy);
        let large = engine.calculate_decay(10_000, 30, &policy);
        assert!(large > small * 50); // roughly proportional
    }

    #[test]
    fn preview_shows_exempt() {
        let engine = DemurrageEngine::new();
        let mut ledger = Ledger::new();
        let policy = test_policy();
        ledger.credit(
            "alice",
            5,
            crate::balance::TransactionReason::Initial,
            None,
        );
        let preview = engine.preview("alice", &ledger, &policy);
        assert!(preview.is_exempt());
        assert_eq!(preview.decay_amount, 0);
    }

    #[test]
    fn run_cycle_processes_all_accounts() {
        let policy = FortunePolicy::testing(); // fast demurrage
        let mut treasury = test_treasury(&policy);
        let mut ledger = Ledger::new();
        let mut engine = DemurrageEngine::new();

        // Create accounts with initial balances
        for i in 0..5 {
            let pubkey = format!("user_{i}");
            treasury
                .mint(1000, &pubkey, crate::treasury::MintReason::Initial)
                .unwrap();
            ledger.credit(
                &pubkey,
                1000,
                crate::balance::TransactionReason::Initial,
                None,
            );
            // Note: days_since returns 0 for just-created accounts,
            // so no decay will apply in this test cycle.
        }

        // Run cycle — since accounts were just created, days_since = 0, so no decay
        let result = engine.run_cycle(&mut ledger, &mut treasury, &policy);
        assert_eq!(result.accounts_processed, 5);
        assert_eq!(result.cycle_number, 1);
        // No decay because last_demurrage is now (days=0)
        assert_eq!(result.total_decayed, 0);
    }

    #[test]
    fn demurrage_feeds_treasury() {
        let policy = test_policy();
        let mut treasury = test_treasury(&policy);
        let mut ledger = Ledger::new();
        let engine = DemurrageEngine::new();

        treasury
            .mint(1000, "alice", crate::treasury::MintReason::Initial)
            .unwrap();
        ledger.credit(
            "alice",
            1000,
            crate::balance::TransactionReason::Initial,
            None,
        );

        // Manually apply decay (simulating time passage)
        let decay = engine.calculate_decay(1000, 30, &policy);
        let actual = ledger.apply_demurrage("alice", decay);
        treasury.receive(actual, ReceiveReason::Demurrage);

        assert_eq!(ledger.balance("alice").liquid, 1000 - actual);
        assert_eq!(treasury.returned_from_demurrage, actual);
    }

    #[test]
    fn high_demurrage_rate_testing() {
        let engine = DemurrageEngine::new();
        let policy = FortunePolicy::testing(); // 10% monthly
        // 1000 Cool, 30 days, 10% monthly
        let decay = engine.calculate_decay(1000, 30, &policy);
        // Should be roughly 100 Cool (10%)
        assert!((90..=110).contains(&decay), "decay was {decay}");
    }
}
